import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../src/components/Navbar'
import Footer from '../src/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>ESAT Landing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      <main className="w-full h-fit">

        {/* First slide */}  

        <div className="flex flex-col bg-[#F2F2F2] w-full h-[705px] py-[316px] gap-y-12">
        <h1 className="text-5xl uppercase text-center">La calidad de la ESAT sin importar <br />donde te encuentres</h1>
        <p className="text-3xl text-center text-[20px]">Nuestros profesores son expertos en su campo y <br />te brindarán la mejor formación en tiempo real, <br />con todas las ventajas de un curso presencial</p>
        <button 
            className="mx-auto w-36 mb-2 px-6 border bg-black py-3 text-white hover:text-black hover:bg-white text-base rounded-lg shadow hover:shadow-lg outline-none focus:outline-none"
            type="button">
            Sign Up
        </button>
        </div>

        {/* Second slide */}

        <div className="flex flex-col flex-wrap bg-[#F2F2F2] w-full h-[905px] pt-[240px] gap-y-12">
        <p className="text-xl text-center">Cursos destacados</p>

        <div className="flex flex-row mx-auto gap-12">
            <div className="flex flex-col gap-y-2">
            <div className="bg-black w-[300px] h-[300px]"></div>
            <p className="text-lg font-bold">Main Title</p>
            <p className="text-base ">Lorem ipsum dolor sit amet, consectetur<br /> adipiscing elit</p>
            <p className="text-sm ">Learn more</p> 
            </div>

            <div className="flex flex-col gap-y-2">
            <div className="bg-black w-[300px] h-[300px]"></div>
            <p className="text-lg font-bold">Main Title</p>
            <p className="text-base ">Lorem ipsum dolor sit amet, consectetur<br /> adipiscing elit</p>
            <p className="text-sm ">Learn more</p> 
            </div>

            <div className="flex flex-col gap-y-2">
            <div className="bg-black w-[300px] h-[300px]"></div>
            <p className="text-lg font-bold">Main Title</p>
            <p className="text-base ">Lorem ipsum dolor sit amet, consectetur<br /> adipiscing elit</p>
            <p className="text-sm ">Learn more</p> 
            </div>
        </div>
        </div>

        {/* Third slide */}

        <div className="flex flex-row w-full h-[905px] px-36 pr-56">
            <div className="flex flex-col pr-48 pl-14 my-auto">

                <h1 className="text-4xl">Cursos online en directo</h1>
                <p className="text-2xl pt-8">En nuestra plataforma, ofrecemos cursos online en directo que te permiten aprender de la mejor manera sin importar dónde te encuentres.</p>
                <p className="text-lg font-light pt-12">¡No te pierdas la oportunidad de aprender de la mejor manera, sin importar dónde te encuentres, con nuestros cursos online en directo de alta calidad!</p>

            </div>
            <div className="flex flex-col ml">
                
                <div className="relative bg-gray-200 left-24 w-[600px] h-[348px] top-48"></div>
                <div className=" relative  bg-black w-[600px] h-[348px] pb-6 bottom-9"></div>
                              
            </div>

        </div>

        {/* Fourth slide */}

        <div className="flex flex-row w-full h-[905px] px-36 gap-y-16 bg-[#F2F2F2]">

            <div className="flex flex-col ml-14">

                <div className="relative bg-white left-24 w-[600px] h-[348px] top-48"></div>
                <div className=" relative  bg-black w-[600px] h-[348px] pb-6 bottom-9"></div>
                              
            </div>

            <div className="flex flex-col pl-48 pr-14 my-auto">

                <h1 className="text-4xl">Participa en las clases</h1>
                <p className="text-2xl pt-8">Podrás participar en las clases y hacer preguntas en tiempo real, lo que te garantiza un aprendizaje más completo y enriquecedor.</p>
                <p className="text-lg font-light pt-12">¡No te pierdas la oportunidad de aprender de la mejor manera, sin importar dónde te encuentres, con nuestros cursos online en directo de alta calidad!</p>

            </div>

        </div>

        {/* Fifth slide */}  

        <div className="flex flex-col bg-white w-full h-[705px] py-auto pt-48 gap-y-12">
        <h1 className="text-3xl font-bold text-center">¿Empezamos?</h1>
        <p className="text-2xl text-center">Transforma tu futuro con la educación de calidad de ESAT. <br />¡Inscríbete hoy y comienza a construir el camino hacia el éxito!</p>
        <button 
            className="mx-auto w-36 mb-2 px-6 border bg-black py-3 text-white hover:text-black hover:bg-white text-base rounded-lg shadow hover:shadow-lg outline-none focus:outline-none"
            type="button">
            Inscribirse
        </button>
        </div>

        {/* Sixth slide */}

        <div className="flex flex-row w-full h-[905px] bg-[#F2F2F2] px-36 pr-56">

            <div className="flex flex-col pr-48 pl-14 my-auto w-1/2">

                <h1 className="text-7xl font-semibold uppercase">Sé escalable<br />piensa en <br />grande</h1>
                <p className="text-2xl pt-14 pb-12">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                <button 
                 className="w-44 mb-2 px-6 border bg-black py-6 text-white hover:text-black hover:bg-white text-base rounded-lg shadow hover:shadow-lg outline-none focus:outline-none"
                 type="button">
                 Start Free Trial
                 </button>

            </div>
          
                
            <div className="bg-white rounded-lg border-2 border-black w-1/2 h-4/6 my-auto mx-auto z-99">
                <div className="flex flex-row p-4 gap-4">
                  <div className="rounded-full border border-black w-[15px] h-[15px]"></div>
                  <div className="rounded-full border border-black w-[15px] h-[15px]"></div>
                  <div className="rounded-full border border-black w-[15px] h-[15px]"></div>
                </div>
            </div>
                              


        </div>


        {/* Seventh slide */}  

        <div className="flex flex-col bg-white w-full h-[705px] py-auto pt-48 gap-y-12">
        <h1 className="text-3xl text-center">Testimonios</h1>
        <p className="text-2xl text-center">Experiencias reales de estudiantes satisfechos con nuestra escuela</p>
        <div className="flex flex-row gap-14 w-full place-content-evenly pt-20 pl-24 pr-24">
            <div className="bg-black w-1/6 h-24"></div>
            <div className="bg-black w-1/6 h-24"></div>
            <div className="bg-black w-1/6 h-24"></div>
            <div className="bg-black w-1/6 h-24"></div>
            <div className="bg-black w-1/6 h-24"></div>
        </div>
        </div>


        {/* Eigth slide */}

        <div className="flex flex-row w-full h-[1300px] px-36 bg-[#F2F2F2]">

            <div className="flex flex-col w-4/6 mx-auto my-auto text-center gap-y-9 ">

                  <h1 className="text-5xl">FAQ</h1>
                  <p className="text-2xl">Obtén respuestas a todas tus preguntas en nuestra sección de preguntas frecuentes</p>

                  <div className="flex flex-col gap-y-1">

                  <div className="flex bg-[#797979] flex-row w-full h-[120px] text-white px-6 rounded-xl">
                    <p className="my-auto text-2xl">Frequently Asked Questions</p>
                    <p className="my-auto ml-auto text-2xl">+</p>
                  </div>

                  <div className="flex bg-[#797979] flex-row w-full h-[120px] text-white px-6">
                    <p className="my-auto text-2xl">Frequently Asked Questions</p>
                    <p className="my-auto ml-auto text-2xl">+</p>
                  </div>

                  <div className="flex bg-[#797979] flex-row w-full h-[120px] text-white px-6">
                    <p className="my-auto text-2xl">Frequently Asked Questions</p>
                    <p className="my-auto ml-auto text-2xl">+</p>
                  </div>

                  <div className="flex bg-white flex-row w-full h-[200px] text-black px-6">
                    <p className="my-auto text-2xl">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,</p>
                  </div>

                  <div className="flex bg-[#797979] flex-row w-full h-[120px] text-white px-6">
                    <p className="my-auto text-2xl">Frequently Asked Questions</p>
                    <p className="my-auto ml-auto text-2xl">+</p>
                  </div>

                  <div className="flex bg-[#797979] flex-row w-full h-[120px] text-white px-6">
                    <p className="my-auto text-2xl">Frequently Asked Questions</p>
                    <p className="my-auto ml-auto text-2xl">+</p>
                  </div>

                  </div>


                              
            </div>

        </div>
        
        <Footer />

      </main>
    </>
  )
}
